apiVersion: 1

datasources:
  - name: Infinity Weather
    uid: infinity-weather
    type: yesoreyeram-infinity-datasource
    access: proxy
    # Permitir chamadas ao Open-Meteo via Infinity
    jsonData:
      allowedHosts:
        - https://api.open-meteo.com
