apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: agro-org
      defaultBucket: sensores
    secureJsonData:
      token: influx-token
